name: Upload results to Ibutsu
on:
  pull_request:
    branches:
      - master
    types:
      - closed
jobs:
  upload:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install required dependencies
        run: npm ci
      - name: Run the tests
        run: npm run test:component
